version: "3"
services:
  kenburnseffect-tool:
    build: .
    ports:
      - "3000:3000"
  mongodb:
    image: mongo:4.4.1
    container_name: mongodb
    ports:
      - "27717:27017"
    volumes:
      - ./data:/data/db